import {useEffect,useMemo,useState} from 'react'
import {respond,type HostEvent} from './brain'
import {loadMemory,remember,type Memory} from './memory'
import {backendEvent,backendSession,backendStatus,backendTts,backendConfig,backendConfigStatus,backendSchedule,connectEventStream,connectTikTok} from './api'
import {playBase64Audio,speakBrowser,stopAudio} from './avatar'
import {AvatarStage} from './AvatarStage'
import {HOSTS,getHost,type HostProfile} from './hostStudio'
import './studio.css'

const initial:HostEvent[]=[{type:'follow',viewer:'Ayesha'},{type:'comment',viewer:'Ali',text:'Hi! How are you?'},{type:'gift',viewer:'Sana',gift:'Rose'}]
const labels:Record<string,string>={comment:'💬 Comment',gift:'🎁 Gift',follow:'❤️ Follow',like:'👍 Like',share:'↗ Share',join:'👋 Join',battle:'⚔️ Battle'}
const env=import.meta.env as Record<string,string|undefined>
const blankConfig={OPENAI_API_KEY:'',OPENAI_TTS_MODEL:'gpt-4o-mini-tts',OPENAI_TTS_VOICE:'coral',GEMINI_API_KEY:'',GEMINI_MODEL:'gemini-2.5-flash',TIKTOK_CLIENT_KEY:'',TIKTOK_CLIENT_SECRET:'',TIKTOK_REDIRECT_URI:''};
function loadConfig(){try{return {...blankConfig,...JSON.parse(localStorage.getItem('aitzaz.runtime.config')||'{}')}}catch{return {...blankConfig}}}
function avatarUrl(host:HostProfile){return env[`VITE_AVATAR_MODEL_URL_${host.id.toUpperCase()}`]||env.VITE_AVATAR_MODEL_URL||host.avatarUrl}

export default function App(){
 const[activeHosts,setActiveHosts]=useState(['sara']),[events,setEvents]=useState<HostEvent[]>(initial),[memory,setMemory]=useState<Memory[]>(loadMemory()),[lastReply,setLastReply]=useState('Choose a host and start a test LIVE.'),[speaking,setSpeaking]=useState(false),[provider,setProvider]=useState('checking'),[voice,setVoice]=useState('checking'),[tiktok,setTiktok]=useState('simulator'),[errors,setErrors]=useState<string[]>([]),[live,setLive]=useState(false),[input,setInput]=useState(''),[streamOnline,setStreamOnline]=useState(false)
 const selected=useMemo(()=>activeHosts.map(id=>getHost(id)),[activeHosts])
 const[settingsOpen,setSettingsOpen]=useState(false),[scheduleOpen,setScheduleOpen]=useState(false),[configForm,setConfigForm]=useState<Record<string,string>>(loadConfig),[adminToken,setAdminToken]=useState(localStorage.getItem('aitzaz.admin.token')||''),[configStatus,setConfigStatus]=useState<any>({}),[schedule,setSchedule]=useState({date:'',time:'',duration:'60',topic:'Open conversation'}),[savedMessage,setSavedMessage]=useState('')
 const viewerCount=useMemo(()=>128+events.length*17,[events.length])
 useEffect(()=>{
  backendStatus().then(s=>{setProvider(s.aiProvider);setVoice(s.voice);setTiktok(s.tiktok);if(Array.isArray(s.activeHosts))setActiveHosts(s.activeHosts)}).catch(e=>setErrors(v=>[e.message,...v].slice(0,8)))
  backendConfigStatus().then(setConfigStatus).catch(()=>{}).catch(e=>setErrors(v=>[e.message,...v].slice(0,8)))
  const es=connectEventStream((type,data)=>{
   setStreamOnline(true)
   if(type==='session.changed'&&Array.isArray(data.activeHosts))setActiveHosts(data.activeHosts)
   if(type==='tiktok.event'){const e:HostEvent={type:data.type,viewer:data.viewer,text:data.text,gift:data.gift,id:data.id};setEvents(v=>[e,...v].slice(0,30));if(e.viewer&&e.text)setMemory(remember(e.viewer,`Asked: ${e.text}`))}
   if(type==='host.reply'){setLastReply(`${data.hostName||'HOST'}: ${data.text}`);setProvider(data.provider||'openai');if(data.text){setSpeaking(true);if(data.audioBase64)playBase64Audio(data.audioBase64,undefined,()=>setSpeaking(false));else speakBrowser({text:data.text,emotion:data.emotion||'warm',speaking:true},undefined,()=>setSpeaking(false))}}
   if(type==='error')setErrors(v=>[data.message,...v].slice(0,8))
  })
  return()=>{es.close();stopAudio()}
 },[])
 async function chooseHost(id:string){
  const next=activeHosts.includes(id)?activeHosts.filter(x=>x!==id):activeHosts.length<2?[...activeHosts,id]:[activeHosts[0],id]
  const safe=next.length?next:['sara'];setActiveHosts(safe)
  try{await backendSession(safe)}catch(e){setErrors(v=>[(e as Error).message,...v].slice(0,8))}
 }
 async function handle(event:HostEvent){
  setEvents(v=>[event,...v].slice(0,30));if(event.viewer&&event.text)setMemory(remember(event.viewer,`Asked: ${event.text}`))
  try{await backendEvent({...event,hostId:activeHosts[0]})}catch(e){const reply=respond(event,memory.map(m=>m.fact));setLastReply(`${selected[0]?.name||'HOST'}: ${reply.text}`);speakBrowser({...reply,speaking:true},()=>setSpeaking(true),()=>setSpeaking(false));setErrors(v=>[`Backend unavailable; browser fallback used: ${(e as Error).message}`,...v].slice(0,8))}
 }
 function ask(){if(!input.trim())return;handle({type:'comment',viewer:'Test Viewer',text:input.trim()});setInput('')}
 async function testVoice(){const text=`Hi, I'm ${selected[0]?.name||'your AI host'}. Voice test is working.`;try{const out=await backendTts(text,selected[0]?.voice);setSpeaking(true);playBase64Audio(out.audioBase64,undefined,()=>setSpeaking(false))}catch{setSpeaking(true);speakBrowser({text,speaking:true},undefined,()=>setSpeaking(false))}}
 async function saveSettings(){try{localStorage.setItem('aitzaz.runtime.config',JSON.stringify(configForm));localStorage.setItem('aitzaz.admin.token',adminToken);await backendConfig(adminToken,configForm);setSavedMessage('Saved to backend ✓');setConfigStatus(await backendConfigStatus())}catch(e){setSavedMessage((e as Error).message)}}
 async function scheduleLive(){try{const out=await backendSchedule({hostIds:activeHosts,date:schedule.date,time:schedule.time,duration:Number(schedule.duration),topic:schedule.topic});setSavedMessage(`Scheduled ${out.schedule.hostIds.map((x:string)=>getHost(x).name).join(' + ')} ✓`);setScheduleOpen(false)}catch(e){setSavedMessage((e as Error).message)}}
 return <div className="app">
  <header><div><div className="brand">AITZAZ <span>AI</span></div><div className="sub">MULTI-HOST TIKTOK LIVE STUDIO</div></div><div className="status"><i className={streamOnline?'on':''}/> {tiktok.toUpperCase()} · {streamOnline?'ENGINE ONLINE':'ENGINE READY'} <button className="settingsBtn" onClick={()=>setSettingsOpen(true)}>⚙ Settings</button></div></header>
  <main>
   <section className="studioHero card"><div className="heroText"><div className="live-pill"><b/> {live?'TEST LIVE':'READY'}</div><h1>Choose your AI LIVE hosts.</h1><p>SARA, LUNA, MAYA, ZAYN and ALEX can run solo. Select two for co-host mode: they take turns, react to each other and share one speech floor.</p><div className="actions"><button onClick={()=>setLive(v=>!v)} className={live?'danger':'primary'}>{live?'End Test LIVE':'Start Test LIVE'}</button><button onClick={()=>setScheduleOpen(true)}>📅 Schedule LIVE</button><button onClick={testVoice}>🔊 Test Voice</button></div></div><div className="miniStats"><div><b>{activeHosts.length}</b><span>ACTIVE HOSTS</span></div><div><b>2</b><span>MAX CO-HOSTS</span></div><div><b>{viewerCount}</b><span>SIM VIEWERS</span></div></div></section>
   <section className="card hostLibrary"><div className="title"><span>HOST LIBRARY</span><strong>{activeHosts.length===2?'CO-HOST MODE':'SOLO MODE'}</strong></div><div className="hostCards">{HOSTS.map(host=><button key={host.id} className={activeHosts.includes(host.id)?'hostCard active':'hostCard'} onClick={()=>chooseHost(host.id)}><div className="hostAvatar"><div className="hostGlow" style={{background:host.color}}/><span>{host.name.slice(0,1)}</span></div><div className="hostInfo"><b>{host.name}</b><small>{host.tagline}</small><em>{host.gender} · {host.voice}</em></div><div className="check">{activeHosts.includes(host.id)?'✓':'+'}</div></button>)}</div></section>
   <section className="avatarGrid">{selected.map(host=><div className="avatarPanel card" key={host.id}><div className="avatarPanelHead"><b>{host.name}</b><span>{host.personality}</span></div><AvatarStage modelUrl={avatarUrl(host)} speaking={speaking}/></div>)}</section>
   <section className="grid">
    <div className="card brain"><div className="title"><span>AITZAZ SUPER BRAIN</span><strong>{provider.toUpperCase()}</strong></div><div className="brain-core"><div className="pulse"/><div><b>HOST ORCHESTRATOR</b><small>Scheduler + memory + event priority</small></div></div><div className="provider"><span>Active</span><b>{selected.map(h=>h.name).join(' + ')}</b></div><div className="provider"><span>Voice</span><b>{voice}</b></div></div>
    <div className="card conversation"><div className="title"><span>LIVE CONVERSATION</span><strong>{viewerCount} viewers</strong></div><div className="reply">{lastReply}</div><div className="ask"><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==='Enter'&&ask()} placeholder="Test a viewer question…"/><button onClick={ask}>Send</button></div></div>
    <div className="card events"><div className="title"><span>TIKTOK EVENT ENGINE</span><strong>{tiktok.toUpperCase()}</strong></div><div className="event-buttons">{(['comment','gift','follow','like','share','join','battle'] as const).map(type=><button key={type} onClick={()=>handle(type==='comment'?{type,viewer:'Hassan',text:'Tell me something interesting'}:type==='gift'?{type,viewer:'Maya',gift:'Galaxy'}:{type,viewer:type==='battle'?'Opponent':'Noor'})}>{labels[type]}</button>)}</div><div className="feed">{events.slice(0,8).map((e,i)=><div key={e.id||i}><b>{e.viewer}</b><span>{e.type==='comment'?e.text:e.type==='gift'?'sent '+e.gift:e.type}</span></div>)}</div></div>
    <div className="card memory"><div className="title"><span>VIEWER MEMORY</span><strong>{memory.length} records</strong></div><p>Regular viewers can build persistent context for future replies.</p>{memory.slice(-4).reverse().map((m,i)=><div className="mem" key={i}><b>{m.viewer}</b><span>{m.fact}</span></div>)}</div>
    <div className="card"><div className="title"><span>SYSTEM</span><strong>{speaking?'SPEAKING':'IDLE'}</strong></div><div className="feed"><div><b>Brain</b><span>{provider}</span></div><div><b>Hosts</b><span>{selected.map(h=>h.name).join(' + ')}</span></div><div><b>Avatar</b><span>{selected.every(h=>avatarUrl(h))?'3D models configured':'avatar slots ready'}</span></div><div><b>TikTok</b><span>{tiktok}</span></div></div></div>
    <div className="card"><div className="title"><span>ERROR LOG</span><strong>{errors.length}</strong></div><div className="feed">{errors.length?errors.slice(0,5).map((e,i)=><div key={i}><b>!</b><span>{e}</span></div>):<div><b>✓</b><span>No runtime errors reported.</span></div>}</div></div>
   </section>
  </main>
  {savedMessage&&<div className="toast">{savedMessage}</div>}
  {settingsOpen&&<div className="modalBack" onMouseDown={e=>e.target===e.currentTarget&&setSettingsOpen(false)}><div className="modal card"><div className="title"><span>⚙ AITZAZ SETTINGS</span><button onClick={()=>setSettingsOpen(false)}>✕</button></div><p className="muted">Keys are stored server-side when saved. TikTok client secret and refresh tokens are never placed in the browser bundle.</p><label>Backend Admin Token<input type="password" value={adminToken} onChange={e=>setAdminToken(e.target.value)} placeholder="AITZAZ_ADMIN_TOKEN"/></label><label>OpenAI API Key<input type="password" value={configForm.OPENAI_API_KEY} onChange={e=>setConfigForm({...configForm,OPENAI_API_KEY:e.target.value})}/></label><div className="two"><label>TTS Voice<select value={configForm.OPENAI_TTS_VOICE} onChange={e=>setConfigForm({...configForm,OPENAI_TTS_VOICE:e.target.value})}><option>coral</option><option>nova</option><option>shimmer</option><option>onyx</option><option>echo</option></select></label><label>TTS Model<input value={configForm.OPENAI_TTS_MODEL} onChange={e=>setConfigForm({...configForm,OPENAI_TTS_MODEL:e.target.value})}/></label></div><label>Gemini API Key<input type="password" value={configForm.GEMINI_API_KEY} onChange={e=>setConfigForm({...configForm,GEMINI_API_KEY:e.target.value})}/></label><label>TikTok Client Key<input value={configForm.TIKTOK_CLIENT_KEY} onChange={e=>setConfigForm({...configForm,TIKTOK_CLIENT_KEY:e.target.value})}/></label><label>TikTok Client Secret<input type="password" value={configForm.TIKTOK_CLIENT_SECRET} onChange={e=>setConfigForm({...configForm,TIKTOK_CLIENT_SECRET:e.target.value})}/></label><label>TikTok Redirect URI<input value={configForm.TIKTOK_REDIRECT_URI} onChange={e=>setConfigForm({...configForm,TIKTOK_REDIRECT_URI:e.target.value})} placeholder="https://your-backend.example.com/api/tiktok/callback"/></label><div className="configRow"><span>OpenAI {configStatus.openai?'✓':'—'} · Gemini {configStatus.gemini?'✓':'—'} · TikTok {configStatus.tiktok?'✓':'—'}</span><div><button onClick={connectTikTok} disabled={!configStatus.tiktok}>Connect TikTok</button><button className="primary" onClick={saveSettings}>Save & Test</button></div></div></div></div>}
  {scheduleOpen&&<div className="modalBack" onMouseDown={e=>e.target===e.currentTarget&&setScheduleOpen(false)}><div className="modal card"><div className="title"><span>📅 SCHEDULE AI LIVE SESSION</span><button onClick={()=>setScheduleOpen(false)}>✕</button></div><p className="muted">Select hosts, date and time. The backend will wake the AI session automatically. Actual TikTok LIVE start requires the TikTok capability available to your approved app or a manual LIVE start.</p><div className="selectedHosts">{selected.map(h=><span key={h.id}>{h.name}</span>)}</div><div className="two"><label>Date<input type="date" value={schedule.date} onChange={e=>setSchedule({...schedule,date:e.target.value})}/></label><label>Time<input type="time" value={schedule.time} onChange={e=>setSchedule({...schedule,time:e.target.value})}/></label></div><div className="two"><label>Duration (min)<input type="number" min="1" value={schedule.duration} onChange={e=>setSchedule({...schedule,duration:e.target.value})}/></label><label>Topic<input value={schedule.topic} onChange={e=>setSchedule({...schedule,topic:e.target.value})}/></label></div><button className="primary" onClick={scheduleLive}>Schedule</button></div></div>}
  <footer>AITZAZ AI • Multi-host AI LIVE studio. TikTok OAuth is server-side; LIVE event/start capabilities depend on the TikTok products and scopes approved for your developer app.</footer>
 </div>
}
